"""add user locale

Revision ID: 23d2457e5d11
Revises: None
Create Date: 2014-07-01 00:16:06.620927

"""

# revision identifiers, used by Alembic.
revision = '23d2457e5d11'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('locale', sa.String(length=2), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'locale')
    ### end Alembic commands ###
